# GoReleaser configuration for abp-gen

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: abp-gen
    main: ./cmd/abp-gen
    binary: abp-gen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - 386
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildDate={{.Date}}
      - -X main.GitCommit={{.Commit}}

archives:
  - id: abp-gen-archive
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - examples/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: '🚀 Features'
      regexp: '^feat(\(.+\))?:'
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: '^fix(\(.+\))?:'
      order: 1
    - title: '♻️ Refactoring'
      regexp: '^refactor(\(.+\))?:'
      order: 2
    - title: '⚡ Performance'
      regexp: '^perf(\(.+\))?:'
      order: 3
    - title: '📝 Documentation'
      regexp: '^docs(\(.+\))?:'
      order: 4
    - title: '🧪 Tests'
      regexp: '^test(\(.+\))?:'
      order: 5

release:
  github:
    owner: mohamedhabibwork
    name: abp-gen
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## ABP Code Generator v{{.Version}}
    
    Cross-platform CLI tool for generating ABP Framework C# code.
    
    ### Installation
    
    Download the appropriate binary for your platform below.
    
    ### What's Changed
  footer: |
    **Full Changelog**: https://github.com/mohamedhabibwork/abp-gen/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - name: abp-gen
    tap:
      owner: mohamedhabibwork
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/mohamedhabibwork/abp-gen
    description: "Cross-platform CLI tool for generating ABP Framework C# code"
    license: MIT
    test: |
      system "#{bin}/abp-gen --version"
    install: |
      bin.install "abp-gen"

nfpms:
  - id: abp-gen-nfpm
    package_name: abp-gen
    homepage: https://github.com/mohamedhabibwork/abp-gen
    description: "Cross-platform CLI tool for generating ABP Framework C# code"
    maintainer: Mohamed Habib <mohamedhabibwork@gmail.com>
    license: MIT
    vendor: ABP Code Generator
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: ./README.md
        dst: /usr/share/doc/abp-gen/README.md
      - src: ./examples/schema.json
        dst: /usr/share/doc/abp-gen/examples/schema.json

